### ISSUE TITLE
How do I get price at a certain date denominated in USD?

### ISSUE THREAD

**Issue by classicrob** [Philipinho/CoinGecko-Java#18]
Hi! I'm trying to get the price of Ethereum in USD on a specific date in the past. I've only been able to find examples that show how to get the current price. Any advice?

Thank you!

**Comment by EClaesson** [comment]
The method you need is `getCoinHistoryById(String id, String data, boolean localization)`.
There seems to be a typo in the parameters. The second parameter (data) is the date you want price history for.

The date format used by the CoinGecko API is `dd-mm-yyyy`.

**Comment by classicrob** [comment]
Awesome, thank you!
