### ISSUE TITLE
Handle HTTP 429 error

### ISSUE THREAD

**Issue by clpir3s** [Philipinho/CoinGecko-Java#27]
Can you handle the 429 rate limited.

When you reached the rate limite coingeck doesn't handle the response as json response. 

The response is HTML can you handle this error?
![image](https://user-images.githubusercontent.com/7682220/143789731-e144acc7-3049-4814-9190-4724cdddc209.png)

Improve this else in (com.litesoftwares.coingecko.CoinGeckoApi)

 public <T> T executeSync(Call<T> call) {
        try {
            Response<T> response = call.execute();
            if (response.isSuccessful()) {
                return response.body();
            } else {
                try {
                    CoinGeckoApiError apiError = getCoinGeckoApiError(response);
                    apiError.setCode(response.code());
                    throw new CoinGeckoApiException(apiError);
                } catch (IOException e) {
                    throw new CoinGeckoApiException(response.toString(), e);
                }
            }
        } catch (IOException e) {
            throw new CoinGeckoApiException(e);
        }
    }

**Comment by Philipinho** [comment]
Closing as PR #32 has been merged.

**Comment by clpir3s** [comment]
Many thanks!
