### ISSUE TITLE
getCoinMarketChartRangeById bugged

### ISSUE THREAD

**Issue by SilberSeele** [Philipinho/CoinGecko-Java#33]
Command getCoinMarketChartRangeById() is not working for any input other than "bitcoin".
e.g.
CoinGeckoApiClient client = new CoinGeckoApiClientImpl();
client.getCoinMarketChartRangeById("bitcoin", "eur",
                String.valueOf(1412577232), String.valueOf(1422577232));
           
works as intended.

However

client.getCoinMarketChartRangeById("ethereum", "eur",
                String.valueOf(1412577232), String.valueOf(1422577232));

returns empty fields.

This also applies to the "try it out" examples of the CoinGecko API doc webpage.

**Comment by EClaesson** [comment]
As this is just a client/wrapper for the CoinGecko API we sadly can't help you if the API and examples are returning unexpected data (or none at all). To get in contact with CoinGecko about any problems, you can send an email to **hello+api@coingecko.com**.
