### ISSUE TITLE
/coins/markets order field with hour_24_desc or hour_24_asc has no effecthour

### ISSUE THREAD

**Issue by userLikun** [Philipinho/CoinGecko-Java#9]
![image](https://user-images.githubusercontent.com/13050154/85945562-49dec280-b971-11ea-87f6-aff8053dd841.png)
When I tested the market interface on the official website, I found that sorting by hour_24_asc and hour_24_desc did not seem to work. The order of the two fields price_change_24h and price_change_percentage_24h in the interface return value is still confusing. I want to know which field is sorted by hour_24, if I want to sort by 24h increase and decrease, what should I do?

**Comment by Philipinho** [comment]
This issue has nothing to do with the Java library itself. Closing.
